spring:
  application:
    name: github-repo-scorer
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis

github:
  api:
    token: ${GITHUB_API_TOKEN:}
    connect-timeout: 3s
    read-timeout: 10s
